---
title: 'Antidepressant Analysis: compare the dose-response meta-analysis models'
output: word_document
---


```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE,cache=TRUE}
# Libraries
library(rms) # for rcs()
library(MASS) # for truehist()
library(R2jags)
library(dosresmeta)
library(devtools)
install_github("htx-r/DoseResponseNMA",force=TRUE)
library(DoseResponseNMA)
library(meta)
```

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE,cache=TRUE}

# read data
mydata <-  read.csv('DOSEmainanalysis.csv') ## Because you saved the data in the sam edirectlory you do not need to read them from a path which is specific only to your computer
antidep=mydata[mydata$exc==F,]

#
antidep$studyid <- as.numeric(as.factor(antidep$Study_No))
antidep$nonResponders <- antidep$No_randomised- antidep$Responders
```
 The number of included studies is:
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}
#present some descriptives like the numbe of studies!
cat(length(unique(antidep$Study_No)))
```



```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE,cache=TRUE}
# data processing
# compute relative odds ratio for all studies
createORreference.fun=function(r,n)
{

  logOR=c(0)
  selogOR=c(NA)

  for(i in 2:c(length(n)))
  {
    calculate=metabin(r[i],n[i],r[1],n[1],sm="OR")
    logOR=c(logOR,calculate$TE)
    selogOR=c(selogOR,calculate$seTE)

  }
  return(cbind(logOR=logOR,selogOR=selogOR))
}
logORmat <- sapply(unique(antidep$studyid),function(i) createORreference.fun(antidep$Responders[antidep$studyid==i],antidep$No_randomised[antidep$studyid==i]),simplify = FALSE)
logORmat <- do.call(rbind,logORmat)
antidep$logOR <- c(logORmat[,1])
antidep$selogOR <- c(logORmat[,2])

# Spline transformation
knots = c(10,20,50)
antidep$dose1 <- as.matrix(rcs(antidep$hayasaka_ddd,knots))[,1]
antidep$dose2 <- as.matrix(rcs(antidep$hayasaka_ddd,knots))[,2]

# transform data into jags format
jagsdataRRspline<- makejagsDRmeta(studyid=studyid,logRR,dose1=dose1,dose2=dose2,cases=Responders,noncases=nonResponders,se=selogRR,type=type,data=antidep,Splines=T,new.dose.range = c(5,10))
jagsdataORspline<- makejagsDRmeta(studyid=studyid,logOR,dose1=dose1,dose2=dose2,cases=Responders,noncases=nonResponders,se=selogOR,type=type,data=antidep,Splines=T,new.dose.range = c(5,10))
jagsdataRRlinear<- makejagsDRmeta(studyid=studyid,logRR,dose1=hayasaka_ddd,dose2=NULL,cases=Responders,noncases=nonResponders,se=selogRR,type=type,data=antidep,Splines=F,new.dose.range = c(5,10))
jagsdataORlinear<- makejagsDRmeta(studyid=studyid,logOR,dose1=hayasaka_ddd,dose2=NULL,cases=Responders,noncases=nonResponders,se=selogOR,type=type,data=antidep,Splines=F,new.dose.range = c(5,10))

# new dose for predictions and plot
new.dose <- seq(0,80,1)
new.dose1 <- c(rcs(new.dose,knots)[,1])
new.dose2 <- c(rcs(new.dose,knots)[,2])
```

# Analysis for Risk ratio (RR): linear and splines
## Estimation

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE,cache=TRUE}
##################################################################
#     ANALYSIS: spline RR
#################################################################

## 1.Frequentist
doseresRRsplineFreq <- dosresmeta(formula=logRR~rcs(hayasaka_ddd,knots), proc="1stage",id=Study_No, type='ci',cases=Responders,n=No_randomised,se=selogRR,data=antidep,method = 'reml')


# 2. Bayes with normal likelihood
doseresRRsplineNor <- jags.parallel(data = jagsdataRRspline,inits=NULL,parameters.to.save = c('beta1.pooled','beta2.pooled','tau'),model.file = modelNorSplineDRmeta,
                              n.chains=3,n.iter = 10000000,n.burnin = 200000,DIC=F,n.thin = 15)


# 3. Bayes with binomial likelihood
doseresRRsplineBin <- jags.parallel(data = jagsdataRRspline,inits=NULL,parameters.to.save = c('beta1.pooled','beta2.pooled','tau'),model.file = modelBinSplineDRmetaRR,
                                    n.chains=3,n.iter = 10000000,n.burnin = 200000,DIC=F,n.thin = 15)

#%% combine the three results
beta1fRR <- coef(doseresRRsplineFreq)[1]
beta2fRR <- coef(doseresRRsplineFreq)[2]

beta1nRR <- doseresRRsplineNor$BUGSoutput$mean$beta1.pooled
beta2nRR <- doseresRRsplineNor$BUGSoutput$mean$beta2.pooled

beta1bRR <- doseresRRsplineBin$BUGSoutput$mean$beta1.pooled
beta2bRR <- doseresRRsplineBin$BUGSoutput$mean$beta2.pooled

taubRR <- doseresRRsplineBin$BUGSoutput$mean$tau
taunRR <- doseresRRsplineNor$BUGSoutput$mean$tau
taufRR <- NA


##################################################################
#     ANALYSIS: RR linear
#################################################################

## 1.Frequentist
doseresRRlinearFreq <- dosresmeta(formula=logRR~hayasaka_ddd, proc="1stage",id=Study_No, type='ci',cases=Responders,n=No_randomised,se=selogRR,data=antidep,method = 'reml')


# 2. Bayes with normal likelihood
doseresRRlinearNor <- jags.parallel(data = jagsdataRRlinear,inits=NULL,parameters.to.save = c('beta.pooled','tau'),model.file = modelNorLinearDRmeta,
                                    n.chains=3,n.iter = 10000000,n.burnin = 200000,DIC=F,n.thin = 15)


# 3. Bayes with binomial likelihood
doseresRRlinearBin <- jags.parallel(data = jagsdataRRlinear,inits=NULL,parameters.to.save = c('beta.pooled','tau'),model.file = modelBinLinearDRmetaRR,
                                    n.chains=3,n.iter = 10000000,n.burnin = 200000,DIC=F,n.thin = 15)

#%% combine the three results
betafRR <- coef(doseresRRlinearFreq)[1]

betanRR <- doseresRRlinearNor$BUGSoutput$mean$beta.pooled

betabRR <- doseresRRlinearBin$BUGSoutput$mean$beta.pooled

taunRRL <- doseresRRlinearNor$BUGSoutput$mean$tau

taubRRL <- doseresRRlinearBin$BUGSoutput$mean$tau

taufRRL <- NA


cbind(bayesBin=c(beta1bRR,beta2bRR,taubRR,betabRR),bayesNor=c(beta1nRR,beta2nRR,taunRR,betanRR,taunRRL),Freq=c(beta1fRR,beta2fRR,taufRR,betafRR,taufRRL),rhatNS=doseresRRsplineNor$BUGSoutput$summary[,'Rhat'],rhatBS=doseresRRsplineBin$BUGSoutput$summary[,'Rhat'],rhatNL=doseresRRlinearNor$BUGSoutput$summary[,'Rhat'],rhatBL=doseresRRlinearBin$BUGSoutput$summary[,'Rhat'])

```

## Including Plots
### Check autocorrelation 
#### Spline
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE,cache=TRUE}
par(mfrow=c(3,3))
 # normal
acf(doseresRRsplineNor$BUGSoutput$sims.array[,1,'beta1.pooled'],main='Normal: beta1.pooled')
acf(doseresRRsplineNor$BUGSoutput$sims.array[,1,'beta2.pooled'],main='Normal: beta2.pooled')
acf(doseresRRsplineNor$BUGSoutput$sims.array[,1,'tau'],main='Normal: tau')

 # binomial
acf(doseresRRsplineBin$BUGSoutput$sims.array[,1,'beta1.pooled'],main='Binomial: beta1.pooled')
acf(doseresRRsplineBin$BUGSoutput$sims.array[,1,'beta2.pooled'],main='Binomial: beta2.pooled')
acf(doseresRRsplineBin$BUGSoutput$sims.array[,1,'tau'],main='Binomial: tau')

```
#### Linear
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE,cache=TRUE}
par(mfrow=c(2,2))
 # normal
acf(doseresRRlinearNor$BUGSoutput$sims.array[,1,'beta.pooled'],main='Normal: beta.pooled')
acf(doseresRRsplineNor$BUGSoutput$sims.array[,1,'tau'],main='Normal: tau')

 # binomial
acf(doseresRRlinearBin$BUGSoutput$sims.array[,1,'beta1.pooled'],main='Binomial: beta1.pooled')
acf(doseresRRlinearBin$BUGSoutput$sims.array[,1,'tau'],main='Binomial: tau')

```
### Trace plots
#### Spline
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE,cache=TRUE}
par(mfrow=c(3,3))
## check convergance


# normal: it is not converged!!!!!!!!!!!!!!!!!!!!!!
traceplot(doseresRRsplineNor$BUGSoutput,varname='beta1.pooled')
traceplot(doseresRRsplineNor$BUGSoutput,varname='beta2.pooled')
traceplot(doseresRRsplineNor$BUGSoutput,varname='tau')

# binomial: it is converged
traceplot(doseresRRsplineBin$BUGSoutput,varname='beta1.pooled')
traceplot(doseresRRsplineBin$BUGSoutput,varname='beta2.pooled')
traceplot(doseresRRsplineBin$BUGSoutput,varname='tau')


```
#### Linear
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE,cache=TRUE}
par(mfrow=c(2,2))
## check convergance

# normal:
traceplot(doseresRRlinearNor$BUGSoutput,varname='beta.pooled')
traceplot(doseresRRlinearNor$BUGSoutput,varname='tau')

# binomial: it is converged
traceplot(doseresRRlinearBin$BUGSoutput,varname='beta.pooled')
traceplot(doseresRRlinearBin$BUGSoutput,varname='tau')

```

### parameters distribution
#### Spline
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE,cache=TRUE}
par(mfrow=c(3,3))
# normal
beta1.pooled.sim.norRR <- c(doseresRRsplineNor$BUGSoutput$sims.array[,,'beta1.pooled']) ## chain 1+2+3 for beta1.pooled
beta2.pooled.sim.norRR <- c(doseresRRsplineNor$BUGSoutput$sims.array[,,'beta2.pooled']) ## chain 1+2+3 for beta2.pooled
tau.sim.norRR <- c(doseresRRsplineNor$BUGSoutput$sims.array[,,'tau']) ## chain 1+2+3 for beta1.pooled

truehist(beta1.pooled.sim.norRR)
truehist(beta2.pooled.sim.norRR)
truehist(tau.sim.norRR)
# binomial
beta1.pooled.sim.binRR <- c(doseresRRsplineBin$BUGSoutput$sims.array[,,'beta1.pooled']) ## chain 1+2+3 for beta1.pooled
beta2.pooled.sim.binRR <- c(doseresRRsplineBin$BUGSoutput$sims.array[,,'beta2.pooled']) ## chain 1+2+3 for beta2.pooled
tau.sim.binRR <- c(doseresRRsplineBin$BUGSoutput$sims.array[,,'tau']) ## chain 1+2+3 for beta2.pooled

truehist(beta1.pooled.sim.binRR)
truehist(beta2.pooled.sim.binRR)
truehist(tau.sim.binRR)
```


#### Linear
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE,cache=TRUE}
par(mfrow=c(3,3))
## beta's distributions
beta.pooled.sim.norRR <- c(doseresRRlinearNor$BUGSoutput$sims.array[,,'beta.pooled']) ## chain 1+2+3 for beta1.pooled
tau.sim.norRRL <- c(doseresRRlinearNor$BUGSoutput$sims.array[,,'tau']) ## chain 1+2+3 for beta1.pooled

truehist(beta.pooled.sim.norRR)
truehist(tau.sim.norRRL)

# binomial
beta.pooled.sim.binRR <- c(doseresRRlinearBin$BUGSoutput$sims.array[,,'beta.pooled']) ## chain 1+2+3 for beta1.pooled
tau.sim.binRRL <- c(doseresRRlinearBin$BUGSoutput$sims.array[,,'tau']) ## chain 1+2+3 for beta1.pooled

truehist(beta.pooled.sim.binRR)
truehist(tau.sim.binRRL)
```

### Compare the three models
#### Spline
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE,cache=TRUE}

# plot the model based on the three apporaches: freq, bayes normal and bayes binomial

plot(new.dose1,exp(beta1fRR*new.dose1+beta2fRR*new.dose2),col=1,type='l',ylim = c(0.5,2)
     ,las=1,ylab='RR',xlab='dose',lwd=3,cex.axis=1.4,cex.lab=1.4) #  freq
lines(exp(beta1nRR*new.dose1+beta2nRR*new.dose2),col=2,lwd=3) # bayes normal
lines(exp(beta1bRR*new.dose1+beta2bRR*new.dose2),col=3,lwd=3) # bayes binomial
legend(10,2,legend=c('Freq', 'normal Bayes', 'binomial Bayes'),col=1:3,horiz = T,lty=1,
       bty='n',xjust = 0.1,cex = 1,lwd=3)
```
#### Linear
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE,cache=TRUE}
plot(new.dose1,exp(betafRR*new.dose1),col=1,type='l',ylim = c(0.5,2)
     ,las=1,ylab='RR',xlab='dose',lwd=3,cex.axis=1.4,cex.lab=1.4) #  freq
lines(exp(betanRR*new.dose1),col=2,lwd=3) # bayes normal
lines(exp(betabRR*new.dose1),col=3,lwd=3) # bayes binomial
legend(10,2,legend=c('Freq', 'normal Bayes', 'binomial Bayes'),col=1:3,horiz = T,lty=1, bty='n',xjust = 0.1,cex = 1,lwd=3)
```


