---
title: 'CODA of normal dose-response MA model with bivariate prior: antidepressant'
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r pp, echo=FALSE, message=FALSE, warning=FALSE}
# normal model: antidepressant 
library(coda)
library(MASS)
library(R2jags)
load('doseresORsplineNorBiv2mio')
m <-as.mcmc(doseresORsplineNorBiv2mio)

# for beta1.pooled , beta2.pooled and tau, the following are some coda plots and measures of them

#*******
# Plots
#*******
par(las=1)

# 1.density
sim.beta1 <-  doseresORsplineNorBiv2mio$BUGSoutput$sims.array[,,'beta1.pooled']
sim.beta2 <-  doseresORsplineNorBiv2mio$BUGSoutput$sims.array[,,'beta2.pooled']
sim.tau <-  doseresORsplineNorBiv2mio$BUGSoutput$sims.array[,,'tau']

truehist(sim.beta1)
lines(density(sim.beta1),lty=1,lwd=3,col=2)
truehist(sim.beta2)
lines(density(sim.beta2),lty=1,lwd=3,col=2)
truehist(sim.tau)
lines(density(sim.tau),lty=1,lwd=3,col=2)


# 2.traceplots
coda::traceplot(m[,'beta1.pooled',drop(FALSE)])
coda::traceplot(m[,'beta2.pooled',drop(FALSE)])
coda::traceplot(m[,'tau',drop(FALSE)])

# 3.geweke plot
geweke.plot(m[,'beta1.pooled',drop(FALSE)])
geweke.plot(m[,'beta2.pooled',drop(FALSE)])
geweke.plot(m[,'tau',drop(FALSE)])

# 4.gelman plot
gelman.plot(m[,'beta1.pooled',drop(FALSE)],ylim=c(1,3.8))
gelman.plot(m[,'beta2.pooled',drop(FALSE)])
gelman.plot(m[,'tau',drop(FALSE)],ylim=c(1,3.8))

#*******
# measures
#*******

# 1.gelman reduction factor R_hat
gelman.diag(m[,'beta1.pooled',drop(FALSE)],autoburnin = TRUE)
gelman.diag(m[,'beta2.pooled',drop(FALSE)],autoburnin = TRUE)
gelman.diag(m[,'tau',drop(FALSE)],autoburnin = TRUE)

# 2.effective size
effectiveSize(m[,'beta1.pooled',drop(FALSE)])
effectiveSize(m[,'beta2.pooled',drop(FALSE)])
effectiveSize(m[,'tau',drop(FALSE)])

# 3.Raftery diagnosis measure
raftery.diag(m[,'beta1.pooled',drop(FALSE)])
raftery.diag(m[,'beta2.pooled',drop(FALSE)])
raftery.diag(m[,'tau',drop(FALSE)])

# 4. Heidel diagnosis
heidel.diag(m[,'beta1.pooled',drop(FALSE)])
heidel.diag(m[,'beta2.pooled',drop(FALSE)])
heidel.diag(m[,'tau',drop(FALSE)])

```


