---
title: "Histograms of OR spline parameters"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown




## Including Plots


```{r pressure, echo=FALSE}
# plot OR spline histogram for simulations
############################################################################
# Histogram of both betas in normal and binomial models over all scenarios
####
library(MASS)
rval <- read.csv("~/Google Drive/DoseResponseNMA/DoseResponsePMA/2019-12-13resORspline40sim1000ALL.csv",header = TRUE)
rval1 <- rval[1:25,-1]
rval2 <- rval[26:50,-1]
rval3 <- rval[51:75,-1]
rval4 <- rval[76:100,-1]
rval5 <- rval[101:125,-1]
rval6 <- rval[126:150,-1]
rval7 <- rval[151:175,-1]
rval8 <- rval[176:200,-1]

#rval1$X == rval2$X == rval3$X == rval4$X == rval5$X == rval6$X == rval7$X == rval8$X
#rownames(rval1) <- rownames(rval2) <- rownames(rval3) <- rownames(rval4) <- rownames(rval5) <- rownames(rval6) <- rownames(rval7) <- rownames(rval8) <- (rval$X[1:25])

par(mfrow=c(1,1),las=1,cex.axis=1.3)
beta1.true<- c(0,0.04,0.1,0.2)
beta2.true <- c(0,0,0.03,-0.2 )
tau.true <- c(0.001,0.01)
col2 <- 'limegreen'
lwd=3

######### Binomial
# beta1
col='orchid3'

truehist(unlist(rval1[1,]),col=col,xlab='')
abline(v=beta1.true[1],lwd=lwd,col=col2)

truehist(unlist(rval2[1,]),col=col,xlab = '')
abline(v=beta1.true[2],lwd=lwd,col=col2)

truehist(unlist(rval3[1,]),col=col,xlab = '')
abline(v=beta1.true[3],lwd=lwd,col=col2)

truehist(unlist(rval4[1,]),col=col,xlab = '')
abline(v=beta1.true[4],lwd=lwd,col=col2)

truehist(unlist(rval5[1,]),col=col,xlab = '')
abline(v=beta1.true[1],lwd=lwd,col=col2)

truehist(unlist(rval6[1,]),col=col,xlab = '')
abline(v=beta1.true[2],lwd=lwd,col=col2)

truehist(unlist(rval7[1,]),col=col,xlab = '')
abline(v=beta1.true[3],lwd=lwd,col=col2)

truehist(unlist(rval8[1,]),col=col,xlab = '')
abline(v=beta1.true[4],lwd=lwd,col=col2)


## beta2
col='orchid4'

truehist(unlist(rval1[12,]),col=col,xlab='')
abline(v=beta2.true[1],lwd=lwd,col=col2)

truehist(unlist(rval2[12,]),col=col,xlab = '')
abline(v=beta2.true[2],lwd=lwd,col=col2)

truehist(unlist(rval3[12,]),col=col,xlab = '')
abline(v=beta2.true[3],lwd=lwd,col=col2)

truehist(unlist(rval4[12,]),col=col,xlab = '')
abline(v=beta2.true[4],lwd=lwd,col=col2)

truehist(unlist(rval5[12,]),col=col,xlab = '')
abline(v=beta2.true[1],lwd=lwd,col=col2)

truehist(unlist(rval6[12,]),col=col,xlab = '')
abline(v=beta2.true[2],lwd=lwd,col=col2)

truehist(unlist(rval7[12,]),col=col,xlab = '')
abline(v=beta2.true[3],lwd=lwd,col=col2)

truehist(unlist(rval8[12,]),col=col,xlab = '')
abline(v=beta2.true[4],lwd=lwd,col=col2)


## tau
col='orchid1'

truehist(unlist(rval1[8,]),col=col,xlab='')
abline(v=tau.true[1],lwd=lwd,col=col2)

truehist(unlist(rval2[8,]),col=col,xlab = '')
abline(v=tau.true[1],lwd=lwd,col=col2)

truehist(unlist(rval3[8,]),col=col,xlab = '')
abline(v=tau.true[1],lwd=lwd,col=col2)

truehist(unlist(rval4[8,]),col=col,xlab = '')
abline(v=tau.true[1],lwd=lwd,col=col2)

truehist(unlist(rval5[8,]),col=col,xlab = '')
abline(v=tau.true[2],lwd=lwd,col=col2)

truehist(unlist(rval6[8,]),col=col,xlab = '')
abline(v=tau.true[2],lwd=lwd,col=col2)

truehist(unlist(rval7[8,]),col=col,xlab = '')
abline(v=tau.true[2],lwd=lwd,col=col2)

truehist(unlist(rval8[8,]),col=col,xlab = '')
abline(v=tau.true[2],lwd=lwd,col=col2)







######### Normal
# beta1
par(mfcol=c(1,1),las=1,cex.axis=1.3)


col='orchid3'

truehist(unlist(rval1[2,]),col=col,xlab='')
abline(v=beta1.true[1],lwd=lwd,col=col2)

truehist(unlist(rval2[2,]),col=col,xlab = '')
abline(v=beta1.true[2],lwd=lwd,col=col2)

truehist(unlist(rval3[2,]),col=col,xlab = '')
abline(v=beta1.true[3],lwd=lwd,col=col2)

truehist(unlist(rval4[2,]),col=col,xlab = '')
abline(v=beta1.true[4],lwd=lwd,col=col2)

truehist(unlist(rval5[2,]),col=col,xlab = '')
abline(v=beta1.true[1],lwd=lwd,col=col2)

truehist(unlist(rval6[2,]),col=col,xlab = '')
abline(v=beta1.true[2],lwd=lwd,col=col2)

truehist(unlist(rval7[2,]),col=col,xlab = '')
abline(v=beta1.true[3],lwd=lwd,col=col2)

truehist(unlist(rval8[2,]),col=col,xlab = '',ylim=c(0,25))
abline(v=beta1.true[4],lwd=lwd,col=col2)


## beta2
col='orchid4'

truehist(unlist(rval1[13,]),col=col,xlab='')
abline(v=beta2.true[1],lwd=lwd,col=col2)

truehist(unlist(rval2[13,]),col=col,xlab = '')
abline(v=beta2.true[2],lwd=lwd,col=col2)

truehist(unlist(rval3[13,]),col=col,xlab = '')
abline(v=beta2.true[3],lwd=lwd,col=col2)

truehist(unlist(rval4[13,]),col=col,xlab = '')
abline(v=beta2.true[4],lwd=lwd,col=col2)

truehist(unlist(rval5[13,]),col=col,xlab = '')
abline(v=beta2.true[1],lwd=lwd,col=col2)

truehist(unlist(rval6[13,]),col=col,xlab = '',ylim=c(0,10))
abline(v=beta2.true[2],lwd=lwd,col=col2)

truehist(unlist(rval7[13,]),col=col,xlab = '',ylim=c(0,10))
abline(v=beta2.true[3],lwd=lwd,col=col2)

truehist(unlist(rval8[13,]),col=col,xlab = '')
abline(v=beta2.true[4],lwd=lwd,col=col2)


## tau
col='orchid1'

truehist(unlist(rval1[7,]),col=col,xlab='')
abline(v=tau.true[1],lwd=lwd,col=col2)

truehist(unlist(rval2[7,]),col=col,xlab = '')
abline(v=tau.true[1],lwd=lwd,col=col2)

truehist(unlist(rval3[7,]),col=col,xlab = '')
abline(v=tau.true[1],lwd=lwd,col=col2)

truehist(unlist(rval4[7,]),col=col,xlab = '')
abline(v=tau.true[1],lwd=lwd,col=col2)

truehist(unlist(rval5[7,]),col=col,xlab = '')
abline(v=tau.true[2],lwd=lwd,col=col2)

truehist(unlist(rval6[7,]),col=col,xlab = '')
abline(v=tau.true[2],lwd=lwd,col=col2)

truehist(unlist(rval7[7,]),col=col,xlab = '')
abline(v=tau.true[2],lwd=lwd,col=col2)

truehist(unlist(rval8[7,]),col=col,xlab = '')
abline(v=tau.true[2],lwd=lwd,col=col2)

######### freq(one-stage)
# beta1
par(mfcol=c(1,1),las=1,cex.axis=1.3)


col='orchid3'

truehist(unlist(rval1[3,]),col=col,xlab='')
abline(v=beta1.true[1],lwd=lwd,col=col2)

truehist(unlist(rval2[3,]),col=col,xlab = '')
abline(v=beta1.true[2],lwd=lwd,col=col2)

truehist(unlist(rval3[3,]),col=col,xlab = '')
abline(v=beta1.true[3],lwd=lwd,col=col2)

truehist(unlist(rval4[3,]),col=col,xlab = '')
abline(v=beta1.true[4],lwd=lwd,col=col2)

truehist(unlist(rval5[3,]),col=col,xlab = '')
abline(v=beta1.true[1],lwd=lwd,col=col2)

truehist(unlist(rval6[3,]),col=col,xlab = '')
abline(v=beta1.true[2],lwd=lwd,col=col2)

truehist(unlist(rval7[3,]),col=col,xlab = '')
abline(v=beta1.true[3],lwd=lwd,col=col2)

truehist(unlist(rval8[3,]),col=col,xlab = '')
abline(v=beta1.true[4],lwd=lwd,col=col2)


## beta2
col='orchid4'

truehist(unlist(rval1[14,]),col=col,xlab='')
abline(v=beta2.true[1],lwd=lwd,col=col2)

truehist(unlist(rval2[14,]),col=col,xlab = '')
abline(v=beta2.true[2],lwd=lwd,col=col2)

truehist(unlist(rval3[14,]),col=col,xlab = '')
abline(v=beta2.true[3],lwd=lwd,col=col2)

truehist(unlist(rval4[14,]),col=col,xlab = '')
abline(v=beta2.true[4],lwd=lwd,col=col2)

truehist(unlist(rval5[14,]),col=col,xlab = '')
abline(v=beta2.true[1],lwd=lwd,col=col2)

truehist(unlist(rval6[14,]),col=col,xlab = '')
abline(v=beta2.true[2],lwd=lwd,col=col2)

truehist(unlist(rval7[14,]),col=col,xlab = '')
abline(v=beta2.true[3],lwd=lwd,col=col2)

truehist(unlist(rval8[14,]),col=col,xlab = '')
abline(v=beta2.true[4],lwd=lwd,col=col2)

#


```

